var instructions_examples = [
    {
      "Initials": "TM",
      "rental_link": "NA",
      "rental_company": "NA",
      "city": "Kenosha, WI",
      "text_prompt": "Create and describe in 75 words a unique vacation rental in Kenosha, WI with the title \" Downtown-Treetop Deck-2Bd/2Bth \" including a detail about the amenities.",
      "text_stimuli (title)": "Downtown-Treetop Deck-2Bd/2Bth",
      "text_stimuli": "This refined third-story residence in historic downtown Kenosha presents 1,100 square feet of modern elegance. The completely updated interior showcases a chef's kitchen with premium quartz surfaces and Viking appliances, complemented by an expansive 400-square-foot private rooftop terrace with Lake Michigan views. Modern conveniences include Nest climate control, digital access, and integrated sound system, steps from HarborPark's dining and waterfront entertainment.",
      "text_type": "AI",
      "text_word_count": 63,
      "gAI_system_texts": "Claude",
      "reword": "Yes",
      "place_prompt": "",
      "place_stimuli": "text_text_and_image_examples/ai_kenosha.jpeg",
      "place_type": "AI",
      "gAI_system_images": "Gemini",
      "face_stimuli": "text_text_and_image_examples/49.S.B.F.png",
      "face_type": "AI",
      "gAI system": "",
      "ai_score": 0
    },
    {
      "Initials": "TM",
      "rental_link": "link",
      "rental_company": "AirBnb",
      "city": "Chicago, IL",
      "text_prompt": "NA",
      "text_stimuli (title)": "Kick back & relax in your home away from home in our modern & peaceful space in the heart of the Bridgeport neighborhood. Featuring incredible natural light, modern amenities & beautiful artwork, the house is impeccably clean and designed to ensure you have the best travel experience possible. Located on popular Morgan Street, you're only blocks away from bakeries, farm-to-table restaurants, independent coffee shops and local breweries.",
      "text_stimuli": "Kick back & relax in your home away from home in our modern & peaceful space in the heart of the Bridgeport neighborhood. Featuring incredible natural light, modern amenities & beautiful artwork, the house is impeccably clean and designed to ensure you have the best travel experience possible. Located on popular Morgan Street, you're only blocks away from bakeries, farm-to-table restaurants, independent coffee shops and local breweries.",
      "text_type": "Human",
      "text_word_count": 64,
      "gAI_system_texts": "NA",
      "reword": "NA",
      "place_prompt": "NA",
      "place_stimuli": "stimuli/place_icon.png",
      "place_type": "Human",
      "gAI_system_images": "NA",
      "face_stimuli": "stimuli/person_icon.png",
      "face_type": "NA",
      "gAI system": "",
      "ai_score": 0
    }
  ]