var AI_task_stim_comments = [
  {
    "Clip_comments": "Groundbreaking advancements in animal imaging technology have revolutionized veterinary care. The introduction of high-resolution scanners and 3D imaging techniques allows for precise diagnosis and treatment of complex conditions in our furry friends. Improved animal welfare is expected as a result.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "40 words",
    "Clip_Prompt_comments": "write me a 40 word news post about animal imaging .",
    "Human_Comment_comments": "Science is fascinating. Im happy that we still have lots of penguins...there is hope that the world will live on for a few more generations",
    "Human_WC_comments": "26 words",
    "AI_Comment_comments": "Wow, this headline is mind-blowing! The advancements in animal imaging showcased here are taking our understanding of the animal kingdom to a whole new level. Can't wait to see the groundbreaking discoveries and improved care that will come out of this!",
    "AI_WC_comments": "41 words",
    "AI_Comment_prompt_comments": "comment on the created headline in the style of a social media comment.",
    "Clip_category_comments": "Past Post, 2012"
  },
  {
    "Clip_comments": "Bourbon Street remains virtually empty ahead of Tropical Storm Isaac in New Orleans, Louisiana. Tropical Storm Isaac is expected to strengthen into at least a Category 1 hurricane before making landfall near Louisiana Tuesday night or early Wednesday..",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "38 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Stay safe Crescent City, was visiting from Chicago last month and want to come back for another visit next year!",
    "Human_WC_comments": "20 words",
    "AI_Comment_comments": "Incredible! This breakthrough will undoubtedly save lives and minimize damage caused by tropical storms. Science for the win!",
    "AI_WC_comments": "18 words",
    "AI_Comment_prompt_comments": "create a 20 word comment on the created headline in the style of a social media comment",
    "Clip_category_comments": "Past Post, 2012"
  },
  {
    "Clip_comments": "Former Enron CEO Jeffrey Skilling, who is serving a 24-year prison term for his role in the energy giant's epic collapse, could get out of prison early under an agreement being discussed by his attorneys and the Justice Department",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "39 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "In today's environment, he wouldn't even be questioned, much less prosecuted.",
    "Human_WC_comments": "11 words",
    "AI_Comment_comments": "This study challenges conventional wisdom and highlights the need for smarter approaches to incarceration and rehabilitation. Thought-provoking!",
    "AI_WC_comments": "17 words",
    "AI_Comment_prompt_comments": "write me a 20 word comment on the created headline in the style of a social media comment \n\"write me a 20 word comment on the created headline in the style of a social media comment \n",
    "Clip_category_comments": "Past Post, 2013"
  },
  {
    "Clip_comments": "Heartwarming adoption story emerges as a family opens their hearts and home to a child in need. The bond formed between the child and their new parents is a testament to the transformative power of love and the joy of creating forever families.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "43 words",
    "Clip_Prompt_comments": "create a 40 word news post highlighting a story about adoption",
    "Human_Comment_comments": "This is far better than leaving the kid to die in a trash can, or keeping it, only to abuse it. I wish more people in the U.S. took advantage of our Safe Haven laws, because there are clearly many people with kids they never wanted, kids they resent, kids they can't stand",
    "Human_WC_comments": "54 words",
    "AI_Comment_comments": "What a beautiful story! Adoption is a testament to the boundless capacity of love and the power of creating meaningful connections. Sending heartfelt congratulations to this incredible family as they embark on their journey of love, growth, and creating lifelong memories.",
    "AI_WC_comments": "42 words",
    "AI_Comment_prompt_comments": "write me a 50 word social media comment about the story created",
    "Clip_category_comments": "Past Post, 2013"
  },
  {
    "Clip_comments": "Are ADHD medications overprescribed? The number of kids treated for ADHD has grown dramatically in recent years. Some are concerned too many children take the medication unnecessarily. Others say ADHD medications are safe and more effective than alternatives. What do you think?",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "42 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "I'd only be concerned what doctors, therapists, and trained experts say, not what un-informed internet tough guys say.",
    "Human_WC_comments": "18 words",
    "AI_Comment_comments": "Insightful research on ADHD! Recognizing its long-term effects emphasizes the need for continuous support and resources for individuals throughout their lives.",
    "AI_WC_comments": "21 words",
    "AI_Comment_prompt_comments": "write me a 25 word comment on the created synopsis \n",
    "Clip_category_comments": "Past Post, 2012"
  },
  {
    "Clip_comments": "In a concerning turn of events, authorities have uncovered a significant rise in illegal weapon possession. Recent incidents highlight the need for stronger measures to tackle the proliferation of firearms, ensuring public safety and reducing the risks associated with their misuse.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "41 words",
    "Clip_Prompt_comments": "create a 45 word news post highlighting a story about weapon possession. Refrain from hashtags",
    "Human_Comment_comments": "The reason they have so many weapons is that they have a \"home\" militia. Every man and woman is armed to defend. Neutrality requires arms!",
    "Human_WC_comments": "25 words",
    "AI_Comment_comments": "The increase in illegal weapon possession is deeply concerning. Strengthening gun control measures and fostering community safety should be top priorities to prevent further harm.",
    "AI_WC_comments": "25 words",
    "AI_Comment_prompt_comments": "write me a 25 word comment on the provided post",
    "Clip_category_comments": "Past Post, 2013"
  },
  {
    "Clip_comments": "Imagine a blimp city floating 30 miles above the scorching surface of Venus. NASA is developing a concept for what could someday be a 30-day manned mission to Earth's closest planetary neighbor.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "33 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Why don't they concentrate on earth instead of wreaking the ozone layer and wasting money flying things into space which is no good to us at all!",
    "Human_WC_comments": "27 words",
    "AI_Comment_comments": "The search for habitable exoplanets continues to captivate our imagination. This discovery brings us one step closer to answering the age-old question: Are we alone in the universe?",
    "AI_WC_comments": "28 words",
    "AI_Comment_prompt_comments": "write me a 25 word comment on the synopsis provided \n",
    "Clip_category_comments": "Past Post, 2014"
  },
  {
    "Clip_comments": "A tense hostage situation unfolds as armed assailants barricade themselves inside a public building. Law enforcement agencies swiftly respond to the crisis, prioritizing the safety of hostages and successfully resolving the situation with no casualties reported.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "36 words",
    "Clip_Prompt_comments": "write a 35 word news synopsis about a hostage situation. refrain from hashtags",
    "Human_Comment_comments": "As an Iranian person, I express my condolences and am very sorry about what happened. Please do not judge Iranian people because what that crazy man did. He was mentally sick. And God bless Australia.",
    "Human_WC_comments": "35 words",
    "AI_Comment_comments": "Kudos to the law enforcement agencies for their swift response and successful resolution of the hostage situation. The safety of the hostages is paramount, and their ability to resolve the crisis without any casualties is commendable",
    "AI_WC_comments": "36 words",
    "AI_Comment_prompt_comments": "write me a 35 word synopsis on the created synopsis",
    "Clip_category_comments": "Past Post, 2014"
  },
  {
    "Clip_comments": "At least 33 people were taken to local hospitals when an out-of-service Chicago Transit Authority train crashed today head-on with another train stopped at a suburban station west of Chicago",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "30 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "it's a good news nobody's got life-threatening injuries. Hope the injured people will get well soon.",
    "Human_WC_comments": "17 words",
    "AI_Comment_comments": "Heartbreaking news. Sending thoughts and prayers to those affected by the train accident. May the injured recover swiftly, and may their loved ones find strength.",
    "AI_WC_comments": "25 words",
    "AI_Comment_prompt_comments": "write me a 20 word comment on the created post \n",
    "Clip_category_comments": "Past Post, 2013"
  },
  {
    "Clip_comments": "Exciting developments in space travel as scientists make significant strides towards commercial space tourism. Companies are advancing reusable rocket technology, pushing the boundaries of human exploration and opening doors for a future where space travel becomes more accessible to all.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "40 words",
    "Clip_Prompt_comments": "write me a 40 word news post about space travel. refrain from hashtags",
    "Human_Comment_comments": "Cheers india...good work.",
    "Human_WC_comments": "4 words",
    "AI_Comment_comments": "The future of space travel!",
    "AI_WC_comments": "5 words",
    "AI_Comment_prompt_comments": "write me a 5 word comment",
    "Clip_category_comments": "Past Post, 2013"
  },
  {
    "Clip_comments": "Silicon Valley has collectively spent at least tens of billions of dollars developing devices like the $3,499 Vision Pro that Apple introduced on Monday and Meta's line of virtual reality goggles called Quest. And face computers are still not a thing.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "42 Words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "At $3499 it's going to be Apple's Galactic Starcruiser- an amazing experience that no one can afford.",
    "Human_WC_comments": "17 words",
    "AI_Comment_comments": "Fascinating read! Silicon Valley's adaptation to remote work and sustainability shows its resilience and capacity for innovation. Exciting times ahead!",
    "AI_WC_comments": "20 words",
    "AI_Comment_prompt_comments": "write me a 20 word comment on the created synopsis \n",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "Heartwarming LGBTQ+ love story takes center stage as a couple overcomes adversity and celebrates their journey. Their resilience and courage inspire acceptance, love, and inclusivity, reminding us of the importance of embracing diversity and supporting equal rights for all.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "39 words",
    "Clip_Prompt_comments": "create a 40 word news post highlighting a story about LGBTQ+",
    "Human_Comment_comments": "Still amazes me in the 21st century that some people think they are being harmed by adults being able to live their lives.",
    "Human_WC_comments": "23 words",
    "AI_Comment_comments": "This story is a powerful reminder of love's triumph over adversity. Celebrating the journey of this LGBTQ+ couple brings us one step closer to a more inclusive and accepting world.",
    "AI_WC_comments": "30 words",
    "AI_Comment_prompt_comments": "write me a 25 word social media comment about the story created",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "The NYPD is still stopping, frisking and searching too many people unlawfully - almost all people of color - despite assurances from Mayor Eric Adams that new policies and training would end the practice, a new report by a court-appointed monitor found.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "40 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Don't know how to react to this. But can we blame them?",
    "Human_WC_comments": "12 words",
    "AI_Comment_comments": "Kudos to the NYPD for prioritizing community engagement and transparency. Building trust is essential for effective policing and safer neighborhoods.",
    "AI_WC_comments": "20 words",
    "AI_Comment_prompt_comments": "write me a 20 word comment on the post presented",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "Exciting news! Scientists unveil a groundbreaking discovery highlighting the critical role of biodiversity in planet health. This finding underscores the urgent need to protect and restore ecosystems for a sustainable future. Let's work together to safeguard our planet for generations to come!",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "42 words",
    "Clip_Prompt_comments": "write me a 40 word social media post about a newsworthy discovery in planet health",
    "Human_Comment_comments": "I'm confused as to why Don't know how to react to this. But can we blame them? anyone thinks this is hilarious. We are running out of resources and ruining the land we live off of. This is something that goes beyond politics.",
    "Human_WC_comments": "31 words",
    "AI_Comment_comments": "This discovery is a wake-up call to prioritize the preservation of our planet's biodiversity. Let's take action to protect ecosystems and secure a healthier future for all living beings",
    "AI_WC_comments": "29 words",
    "AI_Comment_prompt_comments": "write me a 30 word comment about the post created",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "The amount of water stored in more than half of the largest lakes and reservoirs worldwide is declining, a new Science study finds. \nThe results underscore the importance of better water management to protect essential ecosystem services.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "37 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Society must demand concrete actions..., decision makers must generate Environmental Education and science must talk with them and native peoples...",
    "Human_WC_comments": "20 words",
    "AI_Comment_comments": "This is a critical issue that demands immediate attention. Let's raise awareness and take action to ensure equitable access to clean water for all.",
    "AI_WC_comments": "24 words",
    "AI_Comment_prompt_comments": "write me a 20 word comment about the post created \n",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "According to recent reports, a surge in financial success is observed as global markets reach new heights. Rising stock prices, favorable economic indicators, and increased investment opportunities contribute to a positive outlook for businesses and investors worldwide.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "37 words",
    "Clip_Prompt_comments": "using the web, write me a 40 word news story about financial success",
    "Human_Comment_comments": "Yeah I need over a million to retire when I'm 65 if I plan to live to 80-something. So a million at 30 seems off. The advice is still worth something.",
    "Human_WC_comments": "31 words",
    "AI_Comment_comments": "Exciting news for investors and businesses! It's encouraging to see financial success and market growth. Let's hope this positive trend leads to broader economic prosperity for individuals and communities.",
    "AI_WC_comments": "29 words",
    "AI_Comment_prompt_comments": "write me a 20 word comment about the post created",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "The Department of Energy plans to announce Tuesday that scientists have been able for the first time to produce a fusion reaction that creates a net energy gain - a major milestone in the decades-long, multibillion-dollar quest to develop a technology that provides unlimited, cheap, clean power.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "46 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "I didn't think it was possible. I'm sad I won't likely live long enough to see its application used around the world. Through I am glad that my son will benefit from it.",
    "Human_WC_comments": "33 words",
    "AI_Comment_comments": "This discovery is a game-changer in our pursuit of clean energy solutions. With increased efficiency, we can accelerate the transition towards a sustainable future and mitigate the impacts of climate change. Exciting times ahead!",
    "AI_WC_comments": "34 words",
    "AI_Comment_prompt_comments": "write me a 30 word comment that adds to the discussion",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "Stanford University pioneers groundbreaking research in the field of artificial intelligence. Their innovative algorithms are unlocking new possibilities in healthcare, finance, and technology. Stanford's commitment to excellence continues to shape the future and inspire the next generation of leaders.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "39 words",
    "Clip_Prompt_comments": "create a 40 word news post highlighting a story about Stanford University",
    "Human_Comment_comments": "Uncomfortable question: why can't local law enforcement handle law enforcement issues? I think we've all seen more than enough examples of higher education institutes fail to uphold public trust to discredit the system.",
    "Human_WC_comments": "33 words",
    "AI_Comment_comments": "Stanford University's groundbreaking AI research is shaping the future of multiple industries. Their dedication to innovation is commendable and will undoubtedly have a lasting impact on society.",
    "AI_WC_comments": "27 words",
    "AI_Comment_prompt_comments": "write me a 30 word comment on the post presented",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "John Wierwille sprang out of bed early one November morning when he heard coyotes outside his Decatur, Ga., home. But by the time the sheep farmer made it outside to check on his flock, his sheepdogs were already on the scene.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "41 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Good dog! I hope he/she gets a special dinner or maybe an early retirement! Edit: I didn't mean to make light of the dog's situation. He is a hero. No doubt, this was super traumatic for such a young dog.",
    "Human_WC_comments": "41 words",
    "AI_Comment_comments": "Herding dogs are incredible assets to farmers and livestock management. Their innate skills and dedication make them invaluable partners, enhancing efficiency and ensuring the well-being of animals. A testament to the remarkable bond between humans and dogs!",
    "AI_WC_comments": "37 words",
    "AI_Comment_prompt_comments": "write me a 40 word comment adding on to the created synopsis",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "A groundbreaking dental technique is revolutionizing the field of dentistry. This innovative approach offers pain-free procedures and faster recovery times, providing patients with improved oral health and a more comfortable experience. The future of dentistry looks brighter than ever!",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "39 words",
    "Clip_Prompt_comments": "create a 40 word news post highlighting a story about dentistry",
    "Human_Comment_comments": "That's great! I really, really NEED IT! My teeth are worn down flat-with the dentin visible on my front teeth!",
    "Human_WC_comments": "20 words",
    "AI_Comment_comments": "This advancement in dentistry is truly remarkable! Making dental procedures pain-free and improving recovery times will undoubtedly encourage more people to prioritize their oral health. Kudos to the innovators!",
    "AI_WC_comments": "29 words",
    "AI_Comment_prompt_comments": "write me a 30 word comment on the post presented",
    "Clip_category_comments": "Current news"
  },
  {
    "Clip_comments": "A new study has found that naturalistic psychedelic use is associated with specific psychological strengths, suggesting that psychedelics can have positive effects on mental well-being compared to other substances like cannabis and alcohol.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "33 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Interesting, I read in a health book descriptions of what drugs do. All had paragraphs, except for LSD. It simply said ... \" It is like playing Russian Roulette with your mind.\" I read that forever ago, but it stuck.",
    "Human_WC_comments": "38 words",
    "AI_Comment_comments": "This is a promising development in mental health treatment! Exploring the therapeutic potential of naturalistic psychedelics could offer alternative options for those suffering from mental health conditions. Let's continue to support research and prioritize holistic approaches to well-being.",
    "AI_WC_comments": "38 words",
    "AI_Comment_prompt_comments": "adding to the discussion, write me a 40 word social media comment",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "New research reveals promising advancements in COVID-19 treatments and vaccines. Improved antiviral medications and vaccine booster effectiveness are contributing to better disease management. This progress brings hope for controlling the pandemic and safeguarding public health.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "35 words",
    "Clip_Prompt_comments": "using previous findings, write me a 40 word synopsis of a news article focusing on COVID-19",
    "Human_Comment_comments": "There has been a great deal of overreach globally within the medical system since the start of this pandemic. This overreach can only be summed up as medical tyranny. Patients in clinics and hospitals have been declined their preferred method of treatment, denied early intervention protocols or sent home to 'stick it out'",
    "Human_WC_comments": "53 words",
    "AI_Comment_comments": "These advancements in COVID-19 treatments and vaccines offer a glimmer of hope amidst the ongoing pandemic. Let's applaud the relentless efforts of scientists and healthcare professionals who work tirelessly to keep us safe. Together, we can overcome this global challenge and emerge stronger than ever.",
    "AI_WC_comments": "45 words",
    "AI_Comment_prompt_comments": "adding to the discussion, write me a 50 word social media comment",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "Myasthenia gravis is an autoimmune disorder of the nervous system which causes muscle weakness. A new clinical trial suggests that a variation of the advanced blood cancer immunotherapy known as CAR-T (short for chimeric antigen receptor T-cell) could be adapted to treat myasthenia gravis. The modified CAR-T therapy offers the potential for a longer-lasting reduction in symptoms and was well-tolerated without significant adverse effects.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "64 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Why can't they develop therapies that don't cause significant side effects? Oh, because then they wouldn't be able to sell drugs to counter the side effects",
    "Human_WC_comments": "26 words",
    "AI_Comment_comments": "This discovery is a game-changer in the field of autoimmune disorders! Understanding the underlying mechanisms can lead to more effective treatments and improved quality of life for those affected. Exciting times ahead!",
    "AI_WC_comments": "32 words",
    "AI_Comment_prompt_comments": "write me a 30 word comment on the post presented",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "In a significant development, researchers have made a groundbreaking discovery in anemia research. They've identified a previously unknown genetic mutation that affects red blood cell production, shedding light on the underlying causes of certain types of anemia. This breakthrough could pave the way for targeted treatments and improved patient care.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "50 words",
    "Clip_Prompt_comments": "write me a 60 word news post about a newsworthy discovery in anemia",
    "Human_Comment_comments": "Many doctors recommend aspirin for thinning out the blood.\nPeople don't have to take blood thinners, they should instead eat foods that are natural blood thinners. It's safe and much healthier than taking pharmaceutical products for every silly thing.",
    "Human_WC_comments": "39 words",
    "AI_Comment_comments": "This discovery in anemia research is a major breakthrough! Understanding genetic mutations opens doors to more effective treatments and improved outcomes for patients. Exciting progress!",
    "AI_WC_comments": "25 words",
    "AI_Comment_prompt_comments": "adding to the discussion, write me a 25 word social media comment",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "Psoriasis is a skin disorder that causes thick, red, itchy patches of skin. It can sometimes lead to heart disease, arthritis, and other conditions. Scientists used a technique called spatial transcriptomics to gain new insights into the gene and cell differences that contribute to psoriasis. Their findings may also shed light on how severe skin inflammation in one part of the body can lead to problems in other body regions.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "70 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Vitamin D deficiency. You're failing to see the overall deficiency for the disease itself. Notice the woman's pale complexion. All she needs is exposure to sunlight.",
    "Human_WC_comments": "26 words",
    "AI_Comment_comments": "This groundbreaking discovery in Psoriasis research brings hope for better treatments and improved quality of life for those affected by this challenging condition. Science is making progress!",
    "AI_WC_comments": "27 words",
    "AI_Comment_prompt_comments": "adding to the discussion, write me a 25 word social media comment",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "Scientists achieve a groundbreaking discovery in genome research, identifying a gene variant associated with a rare genetic disorder. This finding provides crucial insights into disease mechanisms, paving the way for potential treatments and personalized medicine approaches. The breakthrough holds promise for improved understanding and management of genetic conditions.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "48 words",
    "Clip_Prompt_comments": "write me a 50 word news abstract on a newsworthy discovery in genome research. refrain from hashtags",
    "Human_Comment_comments": "This is a very exciting discovery that will help act as a blueprint for future research. From mapping the world to mapping the human genome... Wow!",
    "Human_WC_comments": "26 words",
    "AI_Comment_comments": "This groundbreaking discovery in genome research brings hope for better understanding and treatment of rare genetic disorders. Science continues to unlock the mysteries of our DNA!",
    "AI_WC_comments": "26 words",
    "AI_Comment_prompt_comments": "write me a 25 word comment on the created abstract",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "A type of bacteria called S. sputigena helps another contributor to tooth decay to form biofilms and produce damaging acid. Breaking the relationship between these two species may be a new strategy for preventing dental cavities.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "36 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Just stop eating and drinking sugary substances and problem solved. Or continue to eat and drink unhealthy and live with the consequences. Your choice.",
    "Human_WC_comments": "24 words",
    "AI_Comment_comments": "The intricate relationship between the human microbiome and our health continues to fascinate. Understanding the role of this bacteria opens up new avenues for developing targeted treatments and enhancing overall well-being.",
    "AI_WC_comments": "31 words",
    "AI_Comment_prompt_comments": "create a 30 word comment adding to the discussion",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "Exciting breakthrough in cannabis research! Scientists have made a significant discovery, highlighting the potential therapeutic properties of cannabinoids for various medical conditions. The study suggests that specific compounds in cannabis may offer relief for chronic pain and aid in the management of certain ailments. This finding has sparked interest in exploring alternative treatment options and further investigating the medicinal potential of cannabis.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "62 words",
    "Clip_Prompt_comments": "write me a 70-word news post about a newsworthy discovery in cannabis usage. refrain from hashtags",
    "Human_Comment_comments": "Yeah, ok. Propaganda. Thousands of positive medical studies, but they choose this one negative one to post. That kind of says it all right there.",
    "Human_WC_comments": "25 words",
    "AI_Comment_comments": "This discovery in cannabis research underscores the importance of studying its potential benefits for medical purposes. It's crucial to continue research and explore safe and effective uses to improve patient care and well-being.",
    "AI_WC_comments": "33 words",
    "AI_Comment_prompt_comments": "create a 30 word comment adding to the discussion",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "We have just experienced the hottest day ever recorded on Earth, with average global temperature exceeding 17\u00B0C (62.6\u00B0F) for the first time.\nThe average global air temperature recorded 2 metres above Earth's surface hit 17.01\u00B0C (62.62\u00B0F) on 3 July, according to data from the National Oceanic and Atmospheric Administration (NOAA) in the US and compiled by the University of Maine.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "63 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Rubbish! It's cool in UK after a few normal summer days of 20-27C, Europe cool at the moment. Where are 'we' talking about! Come on NS, let's have some real world science, not a one liner from whoever this person is!",
    "Human_WC_comments": "41 words",
    "AI_Comment_comments": "The findings regarding accelerated climate change are deeply concerning. We must recognize the urgency and take bold actions to mitigate its effects. Transitioning to renewable energy, adopting sustainable practices, and fostering global cooperation are critical steps toward a more sustainable and resilient future",
    "AI_WC_comments": "41 words",
    "AI_Comment_prompt_comments": "adding to the discussion, write me a 40 word news comment \n",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "Instances of academic cheating raise concerns over academic integrity. Schools and institutions must strengthen measures to deter and address cheating, emphasizing the importance of ethics, fairness, and the value of genuine learning.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "32 words",
    "Clip_Prompt_comments": "write me a 30 word news post about academic cheating",
    "Human_Comment_comments": "f your doctor cheated his/her way through school would you trust them with your life? Being a criminal and cheating your way through school are two completely different things.",
    "Human_WC_comments": "30 words",
    "AI_Comment_comments": "Maintaining academic integrity is crucial in nurturing a culture of true learning. It's essential to foster an environment that promotes integrity, encourages critical thinking, and rewards genuine accomplishments",
    "AI_WC_comments": "28 words",
    "AI_Comment_prompt_comments": "write me a 30 word comment on the created post expanding the conversation",
    "Clip_category_comments": "Science Post"
  },
  {
    "Clip_comments": "Alzheimer's disease, a prevalent neurodegenerative condition, could have its roots in embryonic development.\n\nThe team grew cortical spheres, akin to human embryonic brains, from CRISPR-edited stem cells harboring familial Alzheimer's disease (fAD) mutations. These mutated spheres developed abnormally, being larger and housing fewer mature neurons.\n\nThe study could allow the understanding and addressing of Alzheimer's at much earlier stages, opening pathways for more effective treatments.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "65 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "More research is needed in what is inherited from our parents/grandparents. Can a few generations of women being on the pill, or other drugs, affect the DNA, RNA, proteins etc. which can cause problems for our children. And what about alcohol problems - this could be from the father or the mother.",
    "Human_WC_comments": "48 words",
    "AI_Comment_comments": "It's crucial to spread awareness about Alzheimer's disease and support those affected. Let's stand together, advocate for research funding, and provide care and understanding to individuals and families impacted by this challenging condition.",
    "AI_WC_comments": "33 words",
    "AI_Comment_prompt_comments": "adding to the discussion, write a 30 word comment \n",
    "Clip_category_comments": "Scientific Blog"
  },
  {
    "Clip_comments": "Methane production reaches alarming levels, contributing to the greenhouse effect and climate change. Scientists stress the urgent need to curb emissions from industrial processes, agriculture, and fossil fuel extraction to mitigate environmental impacts and work towards a sustainable future.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "39 words",
    "Clip_Prompt_comments": "write me a 40 word news post about methane production. Refrain from hashtags",
    "Human_Comment_comments": "So no wildlife is bad, not buffalo, deer, goats, prairie dogs, nothing huh?",
    "Human_WC_comments": "13 words",
    "AI_Comment_comments": "The high levels of methane production are a wake-up call. We must prioritize sustainable practices to combat climate change.",
    "AI_WC_comments": "19 words",
    "AI_Comment_prompt_comments": "write me a 15 word comment",
    "Clip_category_comments": "Scientific Blog"
  },
  {
    "Clip_comments": "Sodom and Gomorrah are two famous cities mentioned in the Hebrew Bible and the Christian New Testament, and there are few who haven't heard of them at one point in their life. Supposedly obliterated in a rain of fire, these two cities are reported to have suffered the wrath of God for their sins, debauchery, and egoism. But did they really exist?",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "62 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "The extinction of cities in this area was scientifically proved, 2021, Nature Reports, as a blast which exploded about 2.5 miles above the city 1,000 times more powerful than the atomic bomb used at Hiroshima.",
    "Human_WC_comments": "37 words",
    "AI_Comment_comments": "The internet has undoubtedly revolutionized the way we practice and engage with religion. It's remarkable to see how technology bridges distances, fosters community, and encourages meaningful conversations about faith. The digital age offers new avenues for spiritual growth and connection.",
    "AI_WC_comments": "40 words",
    "AI_Comment_prompt_comments": "write me a 40 word comment on the created post",
    "Clip_category_comments": "Scientific Blog"
  },
  {
    "Clip_comments": "Bolometers, highly sensitive detectors of electromagnetic radiation, have revolutionized scientific research. Recent advancements in bolometer technology have enabled precise measurements across a wide range of wavelengths, from radio waves to X-rays. Their applications in astrophysics, cosmology, and materials science have yielded invaluable data, deepening our understanding of the universe and enabling breakthrough discoveries.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "53 words",
    "Clip_Prompt_comments": "write me a 50 word news blog about bolometers using previous research",
    "Human_Comment_comments": "Anything that enhances the experience of humans on earth it's always a very good thing to have",
    "Human_WC_comments": "17 words",
    "AI_Comment_comments": "Bolometers are incredible tools for scientific exploration, allowing us to study the universe and unlock its mysteries. The advancements in this technology continue to push the boundaries of knowledge.",
    "AI_WC_comments": "29 words",
    "AI_Comment_prompt_comments": "write me a 30 word comment on the created blog",
    "Clip_category_comments": "Scientific Blog"
  },
  {
    "Clip_comments": "Pulsar timing irregularities reveals hidden gravitational-wave background\n\nThe universe is undulating with a background commotion of gravitational waves that have been emitted by pairs of supermassive black holes. That is according to years' worth of pulsar observations that have been conducted by several teams of radio astronomers.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "47 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "As pulsar timing arrays continue to grow in size and sensitivity, they will be able to detect even fainter gravitational waves, from a wider range of sources. This will give us a much better understanding of the dynamics of the universe & test Einstein's theory of GR.",
    "Human_WC_comments": "46 words",
    "AI_Comment_comments": "Mind-blowing! The confirmation of gravitational waves is a testament to the power of scientific exploration. It's awe-inspiring to think about the cosmic events that generate these ripples and how they provide us with a deeper understanding of the vast universe we live in.",
    "AI_WC_comments": "43 words",
    "AI_Comment_prompt_comments": "write me a 45 word comment on the created post in the style of a social media comment",
    "Clip_category_comments": "Scientific Blog"
  },
  {
    "Clip_comments": "The advent of the internet has ushered in a new digital industrial revolution, transforming the way businesses operate. Online platforms enable seamless global connectivity, e-commerce, and automation, revolutionizing industries such as manufacturing, logistics, and services. This digital revolution continues to reshape our economy, workforce, and everyday lives.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "35 words",
    "Clip_Prompt_comments": "write me a 40 word news post about the industrial revolution using the web",
    "Human_Comment_comments": "The US Capitol was built by Black slaves many of whom were Muslims. Fun history fact.",
    "Human_WC_comments": "16 words",
    "AI_Comment_comments": "The digital industrial revolution has undeniably reshaped our world, bringing convenience, innovation, and new opportunities for businesses and individuals alike.",
    "AI_WC_comments": "20 words",
    "AI_Comment_prompt_comments": "write me a 20 word comment on the created post",
    "Clip_category_comments": "Scientific Blog"
  },
  {
    "Clip_comments": "New research using molecular imaging with 18F-flubatine PET/MRI shows a distinct response to food cues in the brains of obese individuals compared to those of normal-weight individuals.\n\nThe study sheds light on the biological mechanisms of obesity and opens the door to potential targeted treatments. Findings reveal a higher total distribution volume of 18F-flubatine in obese participants' brains when viewing photos of food, suggesting neuroreceptors in the brain could be key targets for obesity treatments.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "76 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Strikes me the brain changes may be MANIFESTATIONS of obesity. Rather than causing obesity, obesity may cause these brain changes. We have data documenting an association. I see none establishing causation.",
    "Human_WC_comments": "31 words",
    "AI_Comment_comments": "Incredible! This breakthrough in biological mechanisms brings us closer to unlocking the mysteries of diseases like cancer. The potential for targeted therapies and personalized medicine is truly inspiring. Science continues to amaze!",
    "AI_WC_comments": "32 words",
    "AI_Comment_prompt_comments": "write a 30 word comment about the created post",
    "Clip_category_comments": "Scientific Blog"
  },
  {
    "Clip_comments": "Brain scans, a crucial tool in neuroscience, continue to advance our understanding of the human mind. Researchers utilize various imaging techniques such as functional MRI and EEG to study brain activity patterns associated with emotions, thoughts, and neurological disorders. These scans provide valuable insights into the intricate workings of the brain, paving the way for innovative treatments and interventions in the field of neuroscience.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "64 words",
    "Clip_Prompt_comments": "write me a 60 word news blog about brain scans",
    "Human_Comment_comments": "What was the control to differentiate emotional pain and physical pain?\n\nPhysical pain can be a causal factor of emotional pain per my experience and vise versa. My understanding is all pain is processed in the same area of the brain:unless this location in the brain has already been determined and subdivided?",
    "Human_WC_comments": "53 words",
    "AI_Comment_comments": "Brain scans are mind-blowing! It's incredible how technology allows us to peek into the mysterious workings of our brains. The insights gained from these scans are invaluable, leading to breakthroughs in understanding emotions and mental health. The future of neuroscience looks brighter thanks to these remarkable advancements.",
    "AI_WC_comments": "47 words",
    "AI_Comment_prompt_comments": "write me a 50 word comment on the created blog in the style of a social media comment",
    "Clip_category_comments": "Scientific Blog"
  },
  {
    "Clip_comments": "Geopolitical Economy Report: Debunked: Media falsely claims China is building spy base in Cuba. Media outlets claimed China is building a secret station in Cuba to spy on the US, citing anonymous intelligence officials. But the Pentagon admitted this story is false. It is part of information war",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "48 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "US military bases are completely surrounded China, so China must install military bases surrounding US.\nUS false fake news had resulted in America invading many countries and killing millions of innocent people around the world.",
    "Human_WC_comments": "35 words",
    "AI_Comment_comments": "Great news for the economy! The impressive growth in manufacturing and housing sectors indicates a robust recovery. It's encouraging to see increased consumer demand and a thriving real estate market. Let's hope this positive trend continues to stimulate economic prosperity.",
    "AI_WC_comments": "40 words",
    "AI_Comment_prompt_comments": "write a 35 word comment on the created abstract",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "New research on planetary formation sheds light on the intriguing process by which planets are born. Scientists have discovered that protoplanetary disks, composed of gas and dust, play a vital role in the formation of planets. Through detailed observations and computer simulations, they have uncovered mechanisms involving gravitational forces and accretion, contributing to our understanding of the intricate processes shaping planetary systems across the universe.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "65 words",
    "Clip_Prompt_comments": "write me a 65 word news abstract about planetary formation. use previous findings",
    "Human_Comment_comments": "Love that scientists remain curious and look for answers to these questions, versus *starting* with the answer and stopping all inquiries. Imagine if we did that throughout history.",
    "Human_WC_comments": "44 words",
    "AI_Comment_comments": "Fascinating! The ongoing discoveries about planetary formation expand our knowledge of the universe and how worlds come into existence. Science continues to unlock the mysteries of our cosmic origins.",
    "AI_WC_comments": "29 words",
    "AI_Comment_prompt_comments": "write me a 30 word comment on the created abstract",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "A suspicious package discovered at a post office in New York City was addressed to former Director of National Intelligence James Clapper, an NYPD source told Fox News. A suspicious package addressed to Sen. Cory Booker, D-N.J., was intercepted earlier in Florida, the FBI said.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "46 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Only a mail order organization could have pulled this off since they had the man power to pull this caper off!\nLet the committees in congress haul all the mail delivery companies especially the mail unions up to testify under a supoena to testify!",
    "Human_WC_comments": "44 words",
    "AI_Comment_comments": "Kudos to the courageous police bomb diffusers for their skillful work in neutralizing the threat. Their dedication to public safety and expertise in handling such dangerous situations is truly commendable. Grateful for their service and the lives they protect.",
    "AI_WC_comments": "39 words",
    "AI_Comment_prompt_comments": "write a 40 word comment on the created abstract \n",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "Several colleges across the country are embarking on ambitious expansion plans to accommodate the growing student population. These projects aim to enhance campus facilities, construct new academic buildings, and improve student amenities. The expansions are expected to provide enhanced learning environments and foster a sense of community.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "47 words",
    "Clip_Prompt_comments": "write a 55 word abstract about college expansions",
    "Human_Comment_comments": "And how many billions of our money is the clown show sitting on?",
    "Human_WC_comments": "13 words",
    "AI_Comment_comments": "Exciting news! College expansions will bring improved resources and opportunities for students. Looking forward to the positive changes.",
    "AI_WC_comments": "18 words",
    "AI_Comment_prompt_comments": "write a 15 word comment about the created abstract",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "A new brush fire sparked along the 118 Freeway in the Santa Susana Pass Monday, scorching approximately 186 acres before firefighters got the flames under control.\nFirefighters from Ventura and Los Angeles counties responded to the blaze, with aerial units dropping water on the freeway as the flames drew close to passing vehicles.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "53 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "I just drove through there yesterday as this was the only way left to get my brother home to Camarillo! Now which way can I go?",
    "Human_WC_comments": "26 words",
    "AI_Comment_comments": "My thoughts are with the residents of Malibu affected by this dangerous brush fire. Grateful for the firefighters' bravery and dedication in protecting lives and homes. Stay safe.",
    "AI_WC_comments": "28 words",
    "AI_Comment_prompt_comments": "write a 25 word comment about the created abstract",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "A prominent military figure, once revered for their leadership, finds themselves facing deranking after undisclosed misconduct comes to light. The consequences include a loss of rank and privileges, emphasizing the military's commitment to accountability and maintaining integrity. This incident serves as a powerful reminder that no one is above the standards of conduct, reinforcing the importance of upholding the principles of honor and discipline within the armed forces.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "66 words",
    "Clip_Prompt_comments": "write me a 70 word news story about military deranking. create a story",
    "Human_Comment_comments": "He got what he deserved...obviously this Marine was out of control...still, putting guys in a dryer and slapping a recruit gets 10 years...of course, they will try to get the suicide changed since the young man was running in fear and jumped to his death...but I still don't get how traitors who abandoned their post in a combat zone and willingly mixed with the enemy get off Scott free",
    "Human_WC_comments": "73 words",
    "AI_Comment_comments": "t's disheartening to see a military officer being demoted due to misconduct. Maintaining the integrity and honor of the armed forces is crucial. This incident emphasizes the importance of upholding military protocols and holding individuals accountable for their actions. Let's support the men and women in uniform who uphold the highest standards and protect our nations.",
    "AI_WC_comments": "56 words",
    "AI_Comment_prompt_comments": "create a 60 word comment on the created story",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "Congressional Republicans are calling for a range of changes to the U.S. tax code, including slashing the corporate tax rate and reducing the number of tax brackets for individuals. The House tax committee is proposing doubling the standard deduction for individuals and families, capping the deduction for state and local property taxes at $10,000 and maintaining the current tax treatment of 401(k) and IRA retirement pension plans.",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "70 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "Everyone that considers themselves middle class should love this. The country as a whole will be much better off.",
    "Human_WC_comments": "19 words",
    "AI_Comment_comments": "These Tax code changes can have profound effects on individuals and the economy. It's crucial to strike a balance that promotes fairness and economic growth",
    "AI_WC_comments": "25 words",
    "AI_Comment_prompt_comments": "write me a 20 word comment on the created abstract",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "In a tragic incident, a mass shooting took place yesterday, resulting in multiple casualties. The shooting occurred at a crowded public venue, leaving the community shocked and grieving. Law enforcement swiftly responded to the scene, apprehending the suspected shooter. Authorities are actively investigating the motive behind this senseless act of violence. The local community has come together to support the victims' families and offer condolences during this difficult time.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "69 words",
    "Clip_Prompt_comments": "write me a 70 word news abstract about a mass shooting. refrain from hashtags",
    "Human_Comment_comments": "My heart goes out to all of these people who died and to their families and friends.\nI'm so very sorry this tragedy continues to harm so many people throughout this world. My heart aches for each of you...",
    "Human_WC_comments": "39 words",
    "AI_Comment_comments": "This is absolutely heartbreaking. My thoughts and prayers go out to the victims and their families. We need to address the issue of gun violence in our society and work towards creating safer communities for everyone.",
    "AI_WC_comments": "36 words",
    "AI_Comment_prompt_comments": "write me a 40 word comment in the style of a social meda comment. Refrain from hashtags",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "Gordon County Fire & Rescue, along with Georgia Forestry, are fighting a large fire in Pine Mountain Farms off of Dempsey Loop in the Sonoraville community. High winds are complicating the situation; please avoid the area while fire personnel work to get the fire under control",
    "Clip_type_comments": "Human",
    "Clip_WC_comments": "45 words",
    "Clip_Prompt_comments": "n/a",
    "Human_Comment_comments": "A special thank you to the Gordon County Fire and Sheriff Department along with GA Forestry that responded so quickly to help contain this fire.",
    "Human_WC_comments": "25 words",
    "AI_Comment_comments": "My heart goes out to the brave firefighters and the beautiful wildlife affected by this devastating forest fire. Stay safe and strong, Yosemite National Park",
    "AI_WC_comments": "25 words",
    "AI_Comment_prompt_comments": "write me a 25 word comment based on the created post",
    "Clip_category_comments": "News Abstract"
  },
  {
    "Clip_comments": "A powerful earthquake struck the coastal region of California, shaking the cities of Los Angeles and San Francisco. The seismic activity caused widespread panic and structural damage to buildings, leading to several injuries. Local authorities swiftly responded, mobilizing emergency services and assessing the extent of the destruction. Residents are urged to remain vigilant as aftershocks continue to be felt, emphasizing the importance of preparedness in earthquake-prone areas.",
    "Clip_type_comments": "AI",
    "Clip_WC_comments": "67 words",
    "Clip_Prompt_comments": "write me a 65 word news post about an earthquake. reference real locations",
    "Human_Comment_comments": "My prayers go out to the victims and all the families that have been affected by the earthquake.",
    "Human_WC_comments": "18 words",
    "AI_Comment_comments": "Sending thoughts and prayers to everyone affected by the earthquake. Stay safe and resilient during this challenging time.",
    "AI_WC_comments": "18 words",
    "AI_Comment_prompt_comments": "write an 18 word comment on the created abstract",
    "Clip_category_comments": "News Abstract"
  }
]