AI_task_stim_nocomments = [
  {
    "Clip_nocomments": "It's hard enough counting animals from the ground-- can you imagine counting them FROM SPACE? This year, scientists counted emperor penguins from satellite photos, finding twice as many as expected, and followed the travels of sea turtles by satellite.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "39 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2012"
  },
  {
    "Clip_nocomments": "BREAKING: Incredible scientific breakthrough in understanding tropical storms! Researchers unveil groundbreaking findings that shed light on previously unknown factors affecting storm intensity and trajectory. This discovery will greatly enhance forecasting accuracy, helping protect communities from the devastating impacts of these natural phenomena.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "42 words",
    "Clip_Prompt_nocomments": "write me a 40 word social media post about a newsworthy discovery in tropical storms",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2012"
  },
  {
    "Clip_nocomments": "A new study examines the effectiveness and impact of long prison sentences on crime rates and rehabilitation. Contrary to popular belief, the research suggests that excessively long sentences may hinder successful reintegration into society and calls for a reevaluation of sentencing practices.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "42 words",
    "Clip_Prompt_nocomments": "using previous findings, write me a 40 word synopsis of a news article focusing on prison sentences",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2013"
  },
  {
    "Clip_nocomments": "Baby abandonment is on the rise in South Korea where an amended adoption law has had an unintended effect. \nMany infants have been left in a 'baby box' in Seoul where mothers can anonymously leave their newborns for adoption.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "39 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2013"
  },
  {
    "Clip_nocomments": "New research examines the long-term impacts of ADHD on individuals. The study reveals that, contrary to previous assumptions, ADHD can persist into adulthood and significantly affect various aspects of life, highlighting the importance of early diagnosis and comprehensive support for those with the condition.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "44 words",
    "Clip_Prompt_nocomments": "using previous findings, write a 40 word synopsis of a news article focusing on ADHD.",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2012"
  },
  {
    "Clip_nocomments": "The U.S. and Switzerland have something in common: long traditions of unusually high levels of weapons possession. And Just like the U.S., a senseless crime has ignited an intense debate among Swiss citizens and lawmakers. \nThis is how Switzerland is dealing with guns:",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "45 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2013"
  },
  {
    "Clip_nocomments": "In a significant planetary discovery, astronomers have identified a potentially habitable exoplanet in a nearby star system. This finding raises intriguing questions about the existence of extraterrestrial life and further fuels our fascination with the cosmos.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "36 words",
    "Clip_Prompt_nocomments": "using previous findings, write a 35-word synopsis of a news article focusing on planetary discovery.",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2014"
  },
  {
    "Clip_nocomments": "BREAKING: Two people, including the hostage-taker, have been killed as the Sydne Siege ends with Australian commandos storming the cafe, local media reports say.\nLoud bangs were heard and terrified people ran from the building",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "34 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2014"
  },
  {
    "Clip_nocomments": "A tragic train accident occurred near the town of Chesterfield, resulting in multiple casualties and injuries. The derailment took place during rush hour, causing significant disruption to the regional transportation system.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "31 words",
    "Clip_Prompt_nocomments": "write a 30 word news post about a newsworthy train accident. Use real locations",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2013"
  },
  {
    "Clip_nocomments": "The upcoming launch of a spacecraft to Mars by India is likely to stoke the fires of a burgeoning Asian space race.  The Indian Space Research Organisation (ISRO) is making its final preparations to send an orbiter to the Red Planet.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "41 Words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Past Post, 2013"
  },
  {
    "Clip_nocomments": "A comprehensive analysis delves into the evolving landscape of Silicon Valley. The article explores shifting trends, such as the rise of remote work and increased focus on sustainability, reshaping the region's tech culture and highlighting new opportunities for innovation and collaboration.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "41 words",
    "Clip_Prompt_nocomments": "using previous findings, write me a 40 word synopsis of a news article focusing on Silicon Valley",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "The Human Rights Campaign declared a state of emergency for LGBTQ+ people in the U.S.\nSounding the alarm about the current political environment, the organization released a guidebook summarizing laws it deems discriminatory in each state.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "37 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "The New York Police Department (NYPD) implements innovative community policing strategies to strengthen trust and improve public safety. With a focus on engagement, transparency, and accountability, the NYPD strives to build stronger relationships with the communities it serves.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "38 words",
    "Clip_Prompt_nocomments": "write me a 40 word news post about the New York Police Department",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "A team of top scientists says that it has assessed the planet's health against eight key thresholds needed to protect life on Earth and that human activities have led to seven of the eight of the boundaries already being breached.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "40 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "Alarming research reveals the rapid decline of water sources worldwide. Access to clean water is vital for life, yet many communities are facing scarcity. It's time to unite, conserve water, and secure a sustainable future.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "35 words",
    "Clip_Prompt_nocomments": "using previous findings, write me a 40 word social media post  focusing on declining water sources",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "Self-made millionaire Steve Adcock retired early in his mid-30s. He got rich the old-fashioned way, by working a 9-to-5 and saving and investing wisely. He also attributes his financial success to seven unpopular life and money rules.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "37 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "Big news! A groundbreaking discovery in clean energy is revolutionizing the industry. Scientists have unveiled an innovative technology that harnesses renewable sources with unprecedented efficiency, paving the way for a greener future. Let's celebrate this leap towards sustainable energy solutions!",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "40 words",
    "Clip_Prompt_nocomments": "write me a 40 word social media post about a newsworthy discovery in clean energy",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "Katie Meyer was a few months away from graduating from Stanford University when the email landed in her inbox. The captain of the school's soccer team, who had a 3.84 GPA and law school aspirations, would face a disciplinary hearing for allegedly spilling coffee on a football player accused of sexually assaulting one of her teammates.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "57 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "A recent study highlights the remarkable abilities of herding dogs in assisting farmers and livestock management. Their exceptional intelligence, agility, and natural herding instincts contribute to improved efficiency and welfare in agricultural practices. These canine partners prove indispensable in modern farming operations.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "42 words",
    "Clip_Prompt_nocomments": "using previous findings, write me a 40 word synopsis of a news article focusing on herding dogs",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "Enamel is tough enough to resist dents, yet elastic enough not to crack during decades of jaw smashing.\nIt's so incredible that scientists haven't created a substitute that can match it-until last year.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "33 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Current news"
  },
  {
    "Clip_nocomments": "Exciting breakthrough in mental health research as naturalistic psychedelics gain attention for their therapeutic potential. Preliminary studies suggest promising outcomes in treating depression, anxiety, and PTSD. Further exploration could open new doors for alternative and holistic approaches to mental well-being.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "40 words",
    "Clip_Prompt_nocomments": "create a 40 word news post highlighting a story about Stanford University",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "Initial findings from a study of nearly 10,000 Americans, many of whom had COVID-19, have uncovered new details about Long COVID, the post-infection set of conditions that can affect nearly every tissue and organ in the body.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "38 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "In a groundbreaking study, researchers have uncovered a potential breakthrough in understanding autoimmune disorders. They have identified a previously unknown immune cell population that plays a crucial role in triggering and regulating autoimmune responses. This discovery opens doors to novel targeted therapies and brings hope for more effective treatments for those affected by these complex conditions.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "56 words",
    "Clip_Prompt_nocomments": "using previous findings, write me a 60 word synopsis of a news article focusing on COVID-19",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "New research from an NIH-funded clinical trial found that taking low doses of aspirin daily increased the risk of anemia in people aged 65 years and older by approximately 20%. Anemia in older adults is associated with dementia, cognitive decline and depressive symptoms. Given these findings, care providers may want to consider periodic monitoring of red blood cells or hemoglobin",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "60 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "In a significant breakthrough, scientists have made a remarkable discovery in Psoriasis research. They have identified a specific gene variant associated with an increased risk of developing the condition. This finding not only enhances our understanding of the genetic basis of Psoriasis but also opens up possibilities for personalized treatments and improved patient care. The research holds promise for advancing the field and improving the lives of individuals living with Psoriasis.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "71 words",
    "Clip_Prompt_nocomments": "write me a 75 word news abstract on a newsworthy discovery in Psoriasis research. refrain from hashtags",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "Researchers from the Genotype-Tissue Expression (GTEx) Consortium, funded by National Institutes of Health (NIH), have completed a detailed atlas documenting the stretches of human DNA that influence gene expression - a key way in which a person's genome gives rise to an observable trait, like hair color or disease risk.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "49 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "Researchers highlight the significance of a well-known bacteria species in medical research. The bacterium, found in the human gut, plays a crucial role in digestion and immune regulation, leading to potential therapeutic applications in treating certain diseases.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "37 words",
    "Clip_Prompt_nocomments": "create a 40-word news story about an exsisting type of bacteria using the web",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "A new study shows that in the time after first trying cannabis or first misusing prescription drugs, the percentages of young people who develop the corresponding substance use disorder are higher among adolescents (ages 12-17) than young adults (ages 18-25). In addition, 30% of young adults develop a heroin use disorder and 25% develop a methamphetamine use disorder a year after first using heroin or methamphetamine.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "66 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "A startling revelation has emerged from the latest climate change research. Scientists have discovered an unprecedented acceleration in global warming, with rising temperatures exceeding earlier predictions. Extreme weather events, including record-breaking heatwaves and devastating wildfires, are intensifying, posing significant risks to ecosystems and human populations. Urgent international collaboration and comprehensive actions are imperative to curb greenhouse gas emissions and mitigate the far-reaching consequences of this alarming discovery.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "67 words",
    "Clip_Prompt_nocomments": "using the web, write me a 70 word news post about a discovery in rising climate change",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "Research shows that if someone is sleep deprived, overworked, or even just wearing fake designer products, they are more likely to have an ethical slip and end up cheating.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "29 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Science Post"
  },
  {
    "Clip_nocomments": "Alarming statistics reveal the growing impact of Alzheimer's disease on global health. Let's raise awareness and support ongoing research to find effective treatments and ultimately a cure for this devastating condition. Together, we can make a difference.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "37 words",
    "Clip_Prompt_nocomments": "using the web, write me a 40 word social media post about Alzheimers disease",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Scientific Blog"
  },
  {
    "Clip_nocomments": "Cows Have a Methane Problem. Dairy Farmers are Hoping New Innovations Can Help\n\nMethane is 25 times as potent as carbon dioxide when it comes to trapping heat in the atmosphere, and a single cow can belch 220 pounds of it every year.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "43 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Scientific Blog"
  },
  {
    "Clip_nocomments": "Modern religion has embraced the digital era, with the internet playing a significant role in shaping religious practices. Online platforms enable virtual worship, live-streamed sermons, and global religious communities. Social media provides spaces for religious discussions, interfaith dialogue, and sharing spiritual insights. The internet has become a valuable tool for religious education, outreach, and fostering connections, transforming the way people engage with their faith.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "64 words",
    "Clip_Prompt_nocomments": "write me a 60 word news post about modern religion. Use the internet for context",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Scientific Blog"
  },
  {
    "Clip_nocomments": "A new type of bolometer that covers a broad range of microwave frequencies has been created by researchers in Finland. The work builds on previous research by the team and the new technique could potentially characterize background noise sources and thereby help to improve the cryogenic environments necessary for quantum technologies.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "51 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Scientific Blog"
  },
  {
    "Clip_nocomments": "Gravitational waves, predicted by Einstein's theory of general relativity, have continued to captivate researchers. Recent observations from LIGO and Virgo collaborations have confirmed the existence of these ripples in spacetime, caused by cataclysmic cosmic events. The ongoing exploration of gravitational waves pushes the boundaries of astrophysics.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "46 words",
    "Clip_Prompt_nocomments": "write me a 50 word news post about gravitational waves. Use previous research for context",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Scientific Blog"
  },
  {
    "Clip_nocomments": "English industrialist stole iron technique from Black metallurgists\nA process for converting scrap metal into high-quality iron, which was crucial to the Industrial Revolution, was devised by Black metallurgists who were enslaved and transported to Jamaica by the British",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "39 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Scientific Blog"
  },
  {
    "Clip_nocomments": "A groundbreaking discovery in biological mechanisms has shed light on the intricate processes of cellular communication. Researchers have identified a novel signaling pathway that regulates gene expression, which could have significant implications in understanding diseases like cancer. By studying specific proteins and their interactions, scientists have unraveled a crucial mechanism involved in cell growth and differentiation. This discovery opens new avenues for targeted therapies and personalized medicine, offering hope for improved treatments in the future.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "75 words",
    "Clip_Prompt_nocomments": "write me a 75 word news post about a discovery in biological mechanisms. use real examples",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Scientific Blog"
  },
  {
    "Clip_nocomments": "Everyone's brain has a unique 'pain fingerprint'. Using brain scans, researchers found significant differences in the timing, frequency, and location of gamma oscillations - brain waves linked to pain perception.\n\nSurprisingly, some individuals showed no gamma waves at all. This research underscores the extreme variability of pain response among individuals and suggests the potential to identify individual 'pain fingerprints'.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "58 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "Scientific Blog"
  },
  {
    "Clip_nocomments": "The latest economy report reveals promising growth as major industries show positive trends. Manufacturing output surged by 5% in Q2, driven by increased demand for automobiles. The housing sector experienced a 7% rise in home sales, reflecting a healthy real estate market. These indicators suggest a strong recovery and boost confidence in the overall economic outlook.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "56 words",
    "Clip_Prompt_nocomments": "create a 50 word news abstract on an economy report. use real examples",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "Earth may have formed much more rapidly than previously believed after born as tiny millimeter-sized pebbles that accumulated over a period of just a few million years.\n\nThe new theory also implies that rather than water being delivered to Earth by icy comets, this vital ingredient for life is present on our planet due to our young planet thirstily sucking up water from its space environment.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "66 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "In a tense operation, skilled police bomb diffusers successfully neutralized a potentially deadly explosive device in a bustling urban area. Following meticulous procedures, the team deployed specialized equipment to render the bomb safe, ensuring the safety of nearby residents and preventing a potentially catastrophic incident.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "46 words",
    "Clip_Prompt_nocomments": "write a 50 word news abstract about a police bomb diffusing.",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "The UW-Madison College of Engineering receives some 8,000 applicants annually but only has the space and teaching resources to accept about 1,200. The $347 million building would allow the state flagship to graduate at least 1,000 more undergraduate engineers annually, as well as hire more faculty and expand research.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "52 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "A brush fire erupted near the outskirts of Malibu, California, posing a significant threat to nearby communities. The fast-spreading blaze, fueled by dry vegetation and strong winds, led to the evacuation of residents. Firefighters swiftly mobilized to battle the flames, combating challenging terrain and extreme conditions. Efforts continue to contain the fire and protect lives and property.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "57 words",
    "Clip_Prompt_nocomments": "write a 50 word abstract about a brush fire. reference real locations",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "Gunnery Sgt. Joseph Felix will spend the next 10 years in prison after a court-martial sentenced him Friday for abusing recruits at Parris Island, one of whom jumped over a stairwell and fell to his death after Felix slapped him.\n\nFelix will also be reduced in rank to E1, forfeit all pay and allowances, and he will ultimately receive a dishonorable discharge, said Capt. Joshua Pena, a spokesman for Training and Education Command.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "73 word",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "Significant changes to the tax code are on the horizon as lawmakers propose reforms to streamline the system. The revisions aim to simplify tax filing, reduce loopholes, and create a fairer tax structure. These changes could have far-reaching impacts on individuals, businesses, and the overall economy, prompting discussions on economic growth, income redistribution, and government revenue. The potential implications make this an important development to watch.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "66 words",
    "Clip_Prompt_nocomments": "write me a 70 word news abstract about tax code changes",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "At least 39 people were killed and dozens more were wounded when a single gunman attacked a crowded Istanbul nightclub about an hour after midnight on New Year's Day, Turkish officials said.\n\nInterior Minister Suleyman Soylu called it an act of terrorism and said the gunman was still being sought early Sunday.\n\nSixteen of the people killed were foreigners, the Foreign Ministry said; it was not clear if any were Americans.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "71 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "A devastating forest fire is ravaging the picturesque forests of Yosemite National Park, threatening the iconic wilderness. Firefighters from across the region are battling the flames as they spread rapidly through challenging terrain. Evacuation orders are in place to ensure the safety of residents in nearby communities.",
    "Clip_type_nocomments": "AI",
    "Clip_WC_nocomments": "47 words",
    "Clip_Prompt_nocomments": "write me a 45 word news post about a forest fire. reference real locations",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  },
  {
    "Clip_nocomments": "Rescue crews aided by sniffer dogs dug through crumbled homes in Italy Thursday looking for earthquake survivors as the death toll reached 250 and officials anguished over how to secure their ancient towns and modern cities from the country's highly seismic terrain.\n\nAs many as 365 people were injured in the quake that struck at 3:36 a.m. Wednesday, Italy's civil protection service announced.",
    "Clip_type_nocomments": "Human",
    "Clip_WC_nocomments": "65 words",
    "Clip_Prompt_nocomments": "n/a",
    "Human_Comment_nocomments": "",
    "Human_WC_nocomments": "",
    "AI_Comment_nocomments": "",
    "AI_WC_nocomments": "",
    "AI_Comment_prompt_nocomments": "",
    "Clip_category_nocomments": "News Abstract"
  }
]